name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build main.js
      run: clj -m cljs.main --output-to build/main.js --optimizations simple -c foreclojurescript.core

